# Generated by Django 4.2.4 on 2023-08-08 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Archived')], default=1)),
            ],
            options={
                'verbose_name_plural': 'Job Titles',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('work_type', models.IntegerField(choices=[(1, 'Full Time'), (2, 'Part Time')], default=1)),
                ('pay_method', models.IntegerField(choices=[(1, 'Salary'), (2, 'Hourly')], default=1)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_manager', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
                ('contract', models.URLField(blank=True, null=True)),
                ('department', models.IntegerField(choices=[(1, 'Human Resources'), (2, 'Finance'), (3, 'Marketing'), (4, 'Operations'), (5, 'IT')])),
                ('allergies', models.CharField(blank=True, max_length=200, null=True)),
                ('medical_condition', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='static/images/employees')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.jobtitle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('work_type', models.IntegerField(choices=[(1, 'Full Time'), (2, 'Part Time')], default=1)),
                ('pay_method', models.IntegerField(choices=[(1, 'Salary'), (2, 'Hourly')], default=1)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_manager', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
                ('contract', models.URLField(blank=True, null=True)),
                ('department', models.IntegerField(choices=[(1, 'Human Resources'), (2, 'Finance'), (3, 'Marketing'), (4, 'Operations'), (5, 'Information Technology'), (6, 'Grants')])),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.jobtitle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contractor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
