# Generated by Django 4.2.4 on 2023-12-04 16:06

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_contractor_phone_number_employee_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='country',
            field=django_countries.fields.CountryField(default='CA', max_length=2),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='country_origin',
            field=django_countries.fields.CountryField(default='CA', max_length=2),
        ),
        migrations.AlterField(
            model_name='volunteerhour',
            name='location',
            field=models.IntegerField(choices=[(1, 'Remote'), (2, 'Office'), (3, 'At Event')], default=2),
        ),
        migrations.AlterField(
            model_name='volunteerhour',
            name='time_in',
            field=models.TimeField(default='16:06:30'),
        ),
        migrations.AlterField(
            model_name='volunteerhour',
            name='time_out',
            field=models.TimeField(default='16:06:30'),
        ),
    ]
