# Generated by Django 4.2.4 on 2023-08-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_volunteer_volunteeringarea_volunteerskill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerapplication',
            name='skills',
            field=models.ManyToManyField(blank=True, to='hr.volunteerskill'),
        ),
        migrations.AlterField(
            model_name='volunteerhour',
            name='time_in',
            field=models.TimeField(default='10:21:14'),
        ),
        migrations.AlterField(
            model_name='volunteerhour',
            name='time_out',
            field=models.TimeField(default='10:21:14'),
        ),
    ]
