# Generated by Django 4.2.4 on 2023-12-04 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_volunteer_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerhour',
            name='time_in',
            field=models.TimeField(default='16:14:37'),
        ),
        migrations.AlterField(
            model_name='volunteerhour',
            name='time_out',
            field=models.TimeField(default='16:14:37'),
        ),
        migrations.CreateModel(
            name='VacationSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=2023)),
                ('weeks_of_vacation', models.PositiveSmallIntegerField(default=2)),
                ('percentage_salary', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('plan', models.PositiveSmallIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
    ]
