# Generated by Django 4.2.4 on 2023-09-29 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_volunteerapplication_skills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='department',
        ),
        migrations.AlterField(
            model_name='contractor',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='Manager'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='volunteerhour',
            name='time_in',
            field=models.TimeField(default='07:01:55'),
        ),
        migrations.AlterField(
            model_name='volunteerhour',
            name='time_out',
            field=models.TimeField(default='07:01:55'),
        ),
        migrations.CreateModel(
            name='ScheduleEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('home_office', models.CharField(choices=[('home', 'Home'), ('office', 'Office')], max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_type', models.CharField(choices=[('S', 'Sick Leave'), ('V', 'Vacation'), ('H', 'Work from Home'), ('O', 'Day-Off')], max_length=2)),
                ('description', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_leave_request_fk', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('relationship', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_emergency_contact_fk', to='hr.employee')),
            ],
        ),
        migrations.AddField(
            model_name='contractor',
            name='department',
            field=models.ManyToManyField(to='hr.departments'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ManyToManyField(to='hr.departments'),
        ),
    ]
