# Generated by Django 4.2.4 on 2023-12-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_volunteerhour_time_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Archived'), (3, 'Former'), (4, 'Delete')], default=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Archived'), (3, 'Former'), (4, 'Delete')], default=1),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Archived'), (3, 'Former'), (4, 'Delete')], default=1),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Archived'), (3, 'Former'), (4, 'Delete')], default=1),
        ),
        migrations.AlterField(
            model_name='volunteerhour',
            name='time_in',
            field=models.TimeField(default='06:52:49'),
        ),
        migrations.AlterField(
            model_name='volunteerhour',
            name='time_out',
            field=models.TimeField(default='06:52:49'),
        ),
    ]
