# Generated by Django 4.2.4 on 2023-11-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_employee_gender_volunteer_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerhour',
            name='time_in',
            field=models.TimeField(default='04:14:24'),
        ),
        migrations.AlterField(
            model_name='volunteerhour',
            name='time_out',
            field=models.TimeField(default='04:14:24'),
        ),
    ]
