# Generated by Django 4.2.4 on 2023-12-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_alter_leaverequest_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerhour',
            name='time_in',
            field=models.TimeField(default='10:34:46'),
        ),
        migrations.AlterField(
            model_name='volunteerhour',
            name='time_out',
            field=models.TimeField(default='10:34:46'),
        ),
    ]
