# Generated by Django 4.2.4 on 2023-11-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_alter_volunteerhour_time_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerhour',
            name='time_in',
            field=models.TimeField(default='14:52:15'),
        ),
        migrations.AlterField(
            model_name='volunteerhour',
            name='time_out',
            field=models.TimeField(default='14:52:15'),
        ),
    ]
