# Generated by Django 4.2.4 on 2023-12-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_alter_volunteerhour_time_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Archived'), (3, 'Former'), (4, 'Delete'), (5, 'Pending'), (6, 'Accepted'), (7, 'Rejected')], default=5),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Archived'), (3, 'Former'), (4, 'Delete'), (5, 'Pending'), (6, 'Accepted'), (7, 'Rejected')], default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Archived'), (3, 'Former'), (4, 'Delete'), (5, 'Pending'), (6, 'Accepted'), (7, 'Rejected')], default=1),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Archived'), (3, 'Former'), (4, 'Delete'), (5, 'Pending'), (6, 'Accepted'), (7, 'Rejected')], default=1),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Archived'), (3, 'Former'), (4, 'Delete'), (5, 'Pending'), (6, 'Accepted'), (7, 'Rejected')], default=1),
        ),
        migrations.AlterField(
            model_name='volunteerhour',
            name='time_in',
            field=models.TimeField(default='13:29:41'),
        ),
        migrations.AlterField(
            model_name='volunteerhour',
            name='time_out',
            field=models.TimeField(default='13:29:41'),
        ),
    ]
