# Generated by Django 4.2.4 on 2023-12-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_leaverequest_status_alter_contractor_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('policy_type', models.CharField(max_length=150)),
                ('url', models.URLField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Archived'), (3, 'Former'), (4, 'Delete'), (5, 'Pending'), (6, 'Accepted'), (7, 'Rejected'), (8, 'Aprroved')], default=1)),
            ],
            options={
                'verbose_name_plural': 'Policies',
            },
        ),
        migrations.AddField(
            model_name='volunteerhour',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Archived'), (3, 'Former'), (4, 'Delete'), (5, 'Pending'), (6, 'Accepted'), (7, 'Rejected'), (8, 'Aprroved')], default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Archived'), (3, 'Former'), (4, 'Delete'), (5, 'Pending'), (6, 'Accepted'), (7, 'Rejected'), (8, 'Aprroved')], default=1),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Archived'), (3, 'Former'), (4, 'Delete'), (5, 'Pending'), (6, 'Accepted'), (7, 'Rejected'), (8, 'Aprroved')], default=1),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Archived'), (3, 'Former'), (4, 'Delete'), (5, 'Pending'), (6, 'Accepted'), (7, 'Rejected'), (8, 'Aprroved')], default=5),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Archived'), (3, 'Former'), (4, 'Delete'), (5, 'Pending'), (6, 'Accepted'), (7, 'Rejected'), (8, 'Aprroved')], default=1),
        ),
        migrations.AlterField(
            model_name='volunteerhour',
            name='time_in',
            field=models.TimeField(default='06:47:55'),
        ),
        migrations.AlterField(
            model_name='volunteerhour',
            name='time_out',
            field=models.TimeField(default='06:47:55'),
        ),
    ]
