# Generated by Django 4.2.4 on 2023-12-15 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0012_alter_volunteerhour_time_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='updated_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_leave_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policies',
            name='updated_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_policy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='volunteerhour',
            name='updated_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_volunteer_hour', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='volunteerhour',
            name='time_in',
            field=models.TimeField(default='06:22:08'),
        ),
        migrations.AlterField(
            model_name='volunteerhour',
            name='time_out',
            field=models.TimeField(default='06:22:08'),
        ),
    ]
